# Generated by Django 4.2.11 on 2024-03-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=30)),
                ("contact_number", models.CharField(max_length=11)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
