# Generated by Django 3.2.25 on 2024-05-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
