# Generated by Django 3.2.11 on 2024-04-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_people',
            field=models.IntegerField(null=True),
        ),
    ]
