# Generated by Django 3.2.25 on 2024-05-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_reservation_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(max_length=14),
        ),
    ]
