# Generated by Django 3.2.11 on 2024-04-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation_number_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='Unnamed', max_length=30),
        ),
    ]
